/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

import javax.swing.table.DefaultTableModel;
import libreria.Usuarios;

/**
 *
 * @author Bernardo SJ
 */
public class vercursoalumno extends javax.swing.JFrame {

    /**
     * Creates new form vercursoalumno
     */
    DefaultTableModel tabla;
    public vercursoalumno() {
        getContentPane().setBackground(Color.decode("#74101E"));
        initComponents();
        this.setResizable(false);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                inicioAlumno n = new inicioAlumno();
                n.setVisible(true);
            }
        });
        String cabecera[] = {"Id", "Nombre", "Maestro", "Tipo evento", "Lugar","Dia", "Hora Inicio", "Hora Final"};
        tabla=new DefaultTableModel(null,cabecera);
        tablaCursos.setModel(tabla);
        for (int i = 0; i < Usuarios.registro.alumnos.get(Inicio.pos).inscrito.size(); i++) {
            
                String id =  Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getId();
                String nombre =  Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getNombre();
                String maestro = Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getNombreMaestro();
                //int capacidad = Usuarios.registro.eventos.get(i).getCapacidad();
                String tipo = Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getTipoEvento();
                String lugar = Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getLugar();
                String dia=Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getDia();
                String horaI = Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getHoraInicio();
                String horaF = Usuarios.registro.alumnos.get(Inicio.pos).inscrito.get(i).getHoraFinal();
                Object data[] = {id, nombre, maestro,  tipo, lugar,dia, horaI, horaF};
                tabla.addRow(data);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eventos a los que esas inscrito");

        tablaCursos.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public static int pos;
    private void tablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosMouseClicked
      pos=0;
      int fila=tablaCursos.getSelectedRow();
      String id=(String) tabla.getValueAt(fila,0);
      for(int i=0;i<Usuarios.registro.eventos.size();i++){
          if(Usuarios.registro.eventos.get(i).getId().equals(id)){
              pos=i;
          }
      } 
      contenidoEvento obj=new contenidoEvento(1);
      obj.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_tablaCursosMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
